name: Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytest numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Train model if not exists
      run: |
        if [ ! -f "mnist_model.pth" ]; then
          echo "Warning: model.pth not found. Please ensure you commit your trained model."
          exit 1
        fi
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)/src pytest tests/test_model.py -v